### ISSUE TITLE
New release missing causing package outdated with README documentation

### ISSUE THREAD

**Issue by renatobenks** [pauloedurezende/auto-reload-webpack-plugin#2]
According to the latest release, which is [v1.1.0](https://github.com/pauloedurezende/auto-reload-webpack-plugin/releases/tag/1.1.0), the master is ahead of what should be the next version published at NPM. So, I would love to know if the maintenance of this package still is available or should I use another alternative instead, even a fork?

**Comment by pauloedurezende** [comment]
Hi @renatobenks :wave: 

The maintenance in this package is still available and you can expect a new version in the coming weeks. I am also open to ideas for features to add to the project :wink:
